name: Build TarkadFinance APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip python3-venv openjdk-17-jdk unzip wget

    - name: Instalar Buildozer
      run: |
        python3 -m pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload do APK
      uses: actions/upload-artifact@v3
      with:
        name: TarkadFinance-debug.apk
        path: bin/*.apk
